spring.application.name=predictdaily

server.address=0.0.0.0

server.port=${PORT:8080}

spring.main.banner-mode=off

logging.level.root=INFO

astro.ephemeris.path=file:D:/tools/jar/SwissEphemeris/data